version: '3'
services:

  php-fpm:
    build: ./php/
    networks:
      - docker_network-demo
    ports:
      - "9000:9000"
    volumes:
      - ../:/data/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./var/logs/php-fpm:/var/log/php-fpm:rw
      - ./var/logs/phalcon:/var/tmp:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    networks:
      - docker_network-demo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/data/www:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./var/logs/nginx:/var/log/nginx
      - ./nginx/certs/:/etc/nginx/certs
    restart: always
    command: nginx -g 'daemon off;'

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    networks:
      - docker_network-demo
    volumes:
      - ./var/data/mysql:/var/lib/mysql:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./var/logs/mysql:/var/lib/mysql-logs:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - docker_network-demo
    volumes:
      - ./var/data/redis:/data
    restart: always

  memcached:
    build: ./memcached
    ports:
      - "11211:11211"
    networks:
      - docker_network-demo
    restart: always

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_network-demo
    volumes:
      - ./var/data/elasticsearch:/usr/share/elasticsearch/data
    restart: always

networks:
  docker_network-demo: